web:
  build: .
  command: gradle tRW
  ports:
   - "9000:9000"
  volumes:
   - code:/code
  links:
   - db
db:
  image: orchardup/postgresql
  ports:
   - "5432:5432"
  environment:
#   - POSTGRESQL_USER=activiti-db-admin
#   - POSTGRESQL_PASS=rama
   - POSTGRESQL_DB=activiti
